---
language: python
python: "2.7"

sudo: required

env:
  - distribution: centos
    version: 5
    init: /sbin/init
    run_opts: ""

  - distribution: centos
    version: 6
    init: /sbin/init
    run_opts: ""

  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - 'docker pull ${distribution}:${version}'
  - 'docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
