---
- name: Install Remi repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
  tags:
    - remi

- name: Add Remi GPG key
  rpm_key:
    key: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi"
    state: present
  tags:
    - remi
